[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  DISABLE_ESLINT_PLUGIN = "true"
  NEXT_DISABLE_ESLINT = "1"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
